### ISSUE TITLE
áramlástan 3/10

### ISSUE THREAD

**Issue by qiseel** [PE-MK-JAKI-H/MAFGY#12]
Jó napot kívánok!

Ez jó levezetés lenne a 3/10-es feladatnak?
![áram 310](https://user-images.githubusercontent.com/63043062/79682590-d9eee600-8223-11ea-971d-3d29076bb14f.jpg)

**Comment by Szalay** [comment]
Alapvetően rendben van, a számértékek jók. Az ábrát kell majd bővíteni, illetve ezzel összhangban a lendületmegmaradás alkalmazását kellene részletesebben kifejteni (azaz hogy miért lesz a \mu_B = 1/2).

**Comment by qiseel** [comment]
Köszönöm ! Magyarázatnak ezt gondoltam: Az élesfalú nyíláson átfolyó vízsugár keresztmetszete mindig kisebb a nyílás szelvényénél, mert a kifolyónyílás falához simuló áramvonalak csak véges görbületi sugárral változtathatják irányukat.A kifolyósugár ilyenkor összehúzódik. Az összehúzódás mértékét a keresztmetszetek arányával fejezzük ki mu =Avc/A0.Mivel a  Borda-féle kifolyónyílásban az eltérítés 180 fokos, ezért az összehúzódás tényezőjét az impulzustétel alkalmazásával is számítható.

**Comment by Szalay** [comment]
Az utolsó mondat kivételével rendben van. A folyadéksugár eltérülése tényleg 180°-os, de a lendületmegmaradás nem emiatt érvényes, mert az mindig érvényes. Az elhanyagolások sokasága miatt lesz korlátozott a levezetés eredményének érvényessége.
