### ISSUE TITLE
Elkészült feladatok ellenőrzése H16 és H18

### ISSUE THREAD

**Issue by CsHunor** [PE-MK-JAKI-H/MAFGY#13]
Tisztelt Tanár Úr!

Kérem ellenőrizze le a beadott feladataim megoldását és az elkészített dokumentumokat.

Tisztelettel:
Cseresznyés Hunor

**Comment by Szalay** [comment]
Ellenőrzöm a feladataid, megjegyzéseket a forrás mellé írom.

**Comment by Szalay** [comment]
A feladatmegoldásaid menet rendben van, de sok az apróbb hiba, és az ábrákkal elégedetlen vagyok. Az apróbb hibákat javítsd, az ábrákat pedig gondold újra. A Moodle-be töltöttem fel újabb rajzolós anyagot, ami ebbe nsegíthet.
