### ISSUE TITLE
Feladat ellenőrzés 3/9: Megtört lapra ható erő

### ISSUE THREAD

**Issue by PeczerFanni** [PE-MK-JAKI-H/MAFGY#14]
Tisztelt Tanár Úr!

Mellékelten küldöm a Tikz-cel megrajzolt ábrám a 3/9-es feladathoz, szeretném megkérdezni, hogy ez így rendben van-e?

Köszönöm.
![megtört lapra ható](https://user-images.githubusercontent.com/63015351/79694895-ad62ba80-8273-11ea-9287-467d5d94e27e.jpg)

**Comment by Szalay** [comment]
A rajz a cső elejét leszámítva jó, a jelölések viszont rosszak. Az ámétő jele \diameter, a görög fí betű nem átmérőjel. A c és az u kisbetűk és vektorok legyenek. A róból kétféle van, a \varrho-t használd. A két vektort jelölő nyíl legyen vastag (ultra thick).

**Comment by PeczerFanni** [comment]
Tisztelt Tanár Úr!

Feltöltöttem az általam készített feladatot (3/9 Megtört lapra ható erő) a változtatásokkal amiket mondani tetszett. Szeretném kérni a feladatom ellenőrzését és ha még szükséges akkor kérem segítsen, min kell változtatnom benne. Illetve szeretném megkérdezni, hogy ilyen állapotban mennyire elfogadható a feladatom. Köszönöm szépen.

Péczer Fanni

**Comment by Szalay** [comment]
Ellenőriztem, alapvetően rendben van a számítás menete és az eredmények jók. Csak egy nagyobb hiányosság van, illetve van még néhány apróbb hiba. Először jöjjenek az aprób hibák:
1) Az ábrád b) része nem a vektorábra, "Az ellenőrző felület és a ható erők" legyen a neve.
2) Ezen a b) részen nem szükséges feltüntetnia sűrűséget, illetve a c és u sebességvektorokat, és kell is a helyük, mert a J_{BE} nagyobb kellene legyen (erről előre lehet tudni, hogy közel kétszer akkora, mint a kilépő impulzuserők, és hiányzik az F_T támasztóerő, ami meg kerülhet az u helyére.
3) A két kilépő impulzuserő nagysága egyenlő, de eltérő az irányuk. Emiatt nem jelölheted mindegyiket \vec{J}_{KI}-vel. 
4) A középvonalak ezzel a mintával készüljenek: `\draw[dash pattern={on 8mm off 1mm on 0.5mm off 1mm}] (0, -3) -- (0, 8);`
5) A kilépő impulzuserőket középre kellene igazítani, az elleőrző felületet pedig elvinni egészen a lap széléig.
6) A b) ábrából nem következik, hogy a belépő impulzuserő kétszerese a kilépőknek. Ez annak a következménye, hogy a kilpős áramlási sebességet is c-nek vesszük (azaz nem bővül és emiatt nem is lassul a vízsugár), a tömegáram pedig feleződik. Ezt mondjuk később írod is.
7) A (3.4)-es egyenlettől kis v van a víz sűrűségében.
8) A 3.4/5/6 lehet egy egyenlet.
9) A J erő helyén kellene legyen az F_T támasztóerő.
10) Hiányzik az alap erőegyenlet a levezetésből. Ez ennél a feladatnál a négy erőt tartalmazó vektoregyenlet lenne (3 J a baloldalon, F_T a jobb oldalon). Logikailag a megoldás elején lenne a helye.

És a végére a hiányosság, a vektorábra. Ennek a kidolgozásban is a végén kellene lenni, és a kiszámolt számértékek alapján kellene felrajzolni a 4 erővektort. A támasztóerő 34 N lett, úgyhogy egy jó lépték lenne a 2 mm/N, azaz 68 mm lenne az F_T, ami kényelmesen elfér az oldalon.

**Comment by PeczerFanni** [comment]
Tisztelt Tanár Úr!

Javítottam az ön által jelzett apróbb hibákat, illetve pótoltam a hiányosságot, a legújabb verziót feltöltöttem githubra. Magamhoz mérten megpróbáltam egy vektor ábrát létrehozni. Szeretném kérni, hogy ismét nézze meg a feladatomat. Amennyiben megfelelőnek találja, akkor véglegesíteném a feladatom. 

Köszönöm szépen válaszát. 

Tisztelettel: Péczer Fanni

**Comment by Szalay** [comment]
Megnéztem, pontoztam, az eredményt megtalálod a Google-táblázatban. A J impulzuserő, nem impulzus.
