### ISSUE TITLE
Feladat megoldás (ábra nélkül)

### ISSUE THREAD

**Issue by Cindy9811** [PE-MK-JAKI-H/MAFGY#15]
Kedves Tanár Úr!

Feltöltöttem a feladat megoldását, megtetszik nézni, hogy jó-e?
A feladatgyűjteményben más a megoldás, és nem tudom, hogy melyik a helyes.

Előre is köszönöm!
Neptun kódom: R41KZ8

**Comment by Szalay** [comment]
Átnéztem a feladatokat, beleírtam mi a hiba a másodikban. Az apróbb hibákat javítsd ki, tessék utána rajzolni!

**Comment by Cindy9811** [comment]
Rendben!
Nagyon szépen köszönöm a segítséget!!
