### ISSUE TITLE
A javított, végleges megoldás és ábra (4/10) (AUDWOS)

### ISSUE THREAD

**Issue by bertokdani** [PE-MK-JAKI-H/MAFGY#16]
@Szalay Tanár Úr kérem nézze át a munkám, feltöltöttem az ágamra mindent. Kijavítottam az előző kommentjei alapján a hibákat és megrajzoltam az ábrát is. Ha így megfelel és eléri a megfelelő szintet, beadnám a feladatot.

**Comment by Szalay** [comment]
Nos, elkezdtem ellenőrizni, és az első átnézés után kijelenthetem, hogy eddig a tied a legteljesebb megoldás. Komoly hibák nincsenek, néhány apróságot látok csak. Ezeket megjelölöm, és ha kijavítottad, akkor véglegesként elfogadom a beadandót.

**Comment by Szalay** [comment]
Mivel sok apró részletben töltötted fel a megoldás, inkább egyben írom le a hibákat, hogy ne kelljen keresgetni a megjegyzéseket:
1) Az ábra nem a szívócső jelleggörbéje, hanem a kialakítása vagy a vázlata
2) A könyök veszteségtényezőjében legyen nagy K
3) A feladat szövege és az a) pont között legyen egy \vspacve{0.5cm}, hogy ne lógjanak rá a törtes mértékegységek a következő sorra.
4) A lábszelep az ábrán legyen négyzet alakú, és a magasságát tartsd meg, és a széleségét csökkentsd.
5) Az a) rész elé nem kell a Megoldás szó, utána viszont írhatnád, hogy "A veszteség és a p_A nyomás meghatározása"
6) A b)-nél nem kell a sortörés.
7) A szivattyúnak lehetne talpa.

Egy fontos megjegyzésem van a végére, ami részben kérdés is: a feladatnak csak a 75 pontnyi alapvető részét csináltad meg, két sárga feladatrésszel nem akarsz foglalkozni?

**Comment by bertokdani** [comment]
@Szalay Én azt hittem megcsináltam azokat a feladatrészeket is. De ha így elfogadja ha kijavítom a felsorolt hibákat nem szeretnék már vele foglalkozni, mert közelegnek a számonkérések, ezért is igyekeztem a beadandóval. Így ebben a formában milyen jegyre számíthatok?

**Comment by Szalay** [comment]
Nem láttam a megoldásban a csővezeték-jelleggörbét sem egyenlet alakban felírva, sem ábrázolva, csak ez volt az első ábra neve. De az nem jelleggörbe, hanem maga a csővezeték rendszer.

A legfontosabb hiba pedig kimaradt :)
8) A karimás csőkötés duplavonalas, mint egy kondenzátor egy áramkörben. Itt egy kép: http://www.euromix.hu/uploads/katalogusok/rajzjelek/csokotesek%20rajzjelei.jpg

Ha felsorolt hibákat kijavítod, akkor végeredményben 70 % feletti értékelésre számíthaszt.

Azt sajnos meg kell említenem, hogy a HÖK és az oktatási dékánhelyettes felől súlyos, de megalapozatlan kritika érkezett a beadandó feladatokkal kapcsolatban, emiatt nem tudom 100 %-os biztonsággal kijelenteni, hogy a beadandóitok eredményéből jegy is lesz. Ideális esetben a dékánhelyettes belátja, hogy a feladatokkal nincs gond, és ti pedig megkapjátok érte jegyet.

**Comment by bertokdani** [comment]
Köszönöm! Reméljük, nem lesz probléma a jegyekkel. Hamarosan feltöltöm a javított verziót és jelzem alatta kommentben.

**Comment by bertokdani** [comment]
Feltöltöttem a javított, végleges verziót!

**Comment by Szalay** [comment]
A 2/5/6 pontokat nem sikerült tökéletesen kijavítani, maradt egy-két kis k-s veszteségtényező, az a) és b) pontot pedig subsubsection*-nak gondoltam a megadott címekkel.

Az a) pontnál azt írtad, hogy a második \zeta_K felesleges, de nem az, és a számításban figyelembe is vetted. 

Ezektől függetlenül pontoztam a megoldásod, a 75 pontos rész 88 %, ezen felül a 15 pontos sárga részből megvan 5 pont, és bőven a +10 %-os időkorlát előtt vagyunk, így a végeredmény 78,1 %. A részpontokat a Google-táblázatban megtalálod.

**Comment by bertokdani** [comment]
@Szalay nagyon szépen köszönöm!
