### ISSUE TITLE
Elkészített feladat (mdpm86)

### ISSUE THREAD

**Issue by fromhun** [PE-MK-JAKI-H/MAFGY#17]
Tisztelt Tanár Úr! 

A feladatom elkészült kérem annyak ellenörzését. Rajzolás közben belefutottam pár problémába, ha azok nem is feltűnőek.

Két helyen csőkönyök magasság méretezését kellett megoldanom erre nem találtam más használható megoldást mint a méretvonal túllógatása a könyökön. Megoldást jelentene még az is ha a méretvonalat "manuálisan" hosszabbítanám meg annál a szárnál aminél szükségem van rá, de ahhez tudnom kéne milyen vonalvastagságot használ a méretező \pgflength. 

Jelölnöm kellett egy egyes pontot az ábrán ami a feladatgyűjteményben be van karikázva ezt az \textcircled{1} paranccsal tettem meg, de nem túl esztétikus, van rá esetleg más parancs , mert amit én találtam az plusz library-t igényelne.

Egy egyenleten belül lehet sortörést alkalmazni? Az én megoldásommal(külön equation-ként írva) a behelyettesített képletet új számmal látta el.

A feladat magyarázatét igyekeztem egyszerűen megfogalmazni, ha az nem megfelelő átírom.

Valószínűleg sok vektrojelölést kihagytam az egyenletekben ha azok formátuma alapvetően megfelel ezeket pótlom.

Tisztelettel: Vasáros Mátyás

**Comment by Szalay** [comment]
Átnéztem a megoldásod, megjegyzéseket megtalálod az utolsó beküldésnél (commit). A hibák javítása után elfogadható lesz a feladat, viszont ez csak 75 pontos példa, azaz ezzel önmagában legfelljebb 75 %-os eredményt szerezhetsz. Megelégszel ennyivel, választasz még mellé egy 25-öst, vagy esetleg bővítsem ki a feladatot a csővezeték jelleggörbéjével, hogy ne kelljen egy újba belekezdeni?

**Comment by Szalay** [comment]
Ebben a feladatban nincs egyetlen vektor sem :)

**Comment by Szalay** [comment]
Az egyenletek darabolására a split és az align környezeteket lehet használni: https://www.overleaf.com/learn/latex/aligning_equations_with_amsmath

A sablon, amiből kiindultok tartalmazza az AMS csomagokat, működni fog mindkettő.

**Comment by fromhun** [comment]
Tisztelt Tanár Úr!
A hibákat elvileg javítottam és újra feltöltöttem a feladatot.
Egy jelleggörbét szívesen készítenék, de még utána kell járnom a módjának, igyekszem a szorgalmi időszak végéig teljesíteni azt is. 

Tisztelettel: Vasáros Mátyás

**Comment by Szalay** [comment]
A jelleggörbe igazából csak egy másodfokú függvény. A felírása és az ábrázolása sem bonyolult. Ami érdekessé (és 25 pontossá) tenné azt a részt, az a jelelggörbe ábrázolása a tolózár nyitásának függvényében. Ez azt jelentené, hogy nem 1 jelleggörbéd lenne, hanem egy görbesereg, aminek a paraméterea tolózár nyitása mondjuk 25/50/75 és 100 %-nál.

**Comment by Szalay** [comment]
Ránéztem újra a megoldásra, és szerintem nme javítottad mindegyik hibát, vagy nem küldted be/töltötted fel a javított változatot.

**Comment by fromhun** [comment]
Feltöltési hiba volt a következő ellenőrzést csak a jelleggörbék elkészítése után kérem várhatóan a következő héten. 
Köszönöm.
