### ISSUE TITLE
MAFGY H1/20

### ISSUE THREAD

**Issue by Stewie98** [PE-MK-JAKI-H/MAFGY#18]
Tisztelt tanár úr!
Elkészültem a feladattal, szeretném kérni, hogy ellenőrizze le. Kérdezném továbbá, hogy a bekerült ábra illetve a hozzá írt magyarázat megfelelő-e?
Székely Dániel
TDS675

**Comment by Szalay** [comment]
Átnéztem, a megjegyzéseket megtalálod ennél a beküldésnél: https://github.com/PE-MK-JAKI-H/MAFGY/commit/5d8659c7ad994a2d25c90e0934ce25186c30acc4 

Az ábrán kellene meég dolgozni, a többi részben csap apróbb hibák vannak.

A Google-táblázat szerint csak ezt a feladatot választottad, viszont ez csak 50 pontos. Ha teljesen kijavítod, az az elégséges szintre elég lesz, de ha jobbat szeretnél, akkor kellene még egy 50 pontos feladatot választani. Még van egy-két 50 pontos szabad feladat.

**Comment by Stewie98** [comment]
Tisztelt tanár úr!
Az ehhez a feladathoz tartozó végleges megoldást május elején beadtam, (akkor még pull request-el), viszont az eredményt még nem láttam a google táblázatban. Amennyiben erre lehetőség van fel tudná ezt tüntetni? Van még egy elméleti feladatom is, ami nem biztos, hogy kész lesz a határidőig, viszont más tárgyak miatt fontos lenne tudnom, hogy hány pontom van az időm beosztása végett.
Köszönöm!
Székely Dániel
TDS675

**Comment by Szalay** [comment]
Beírtam a pontozást a táblázatba. Figyelembe vettem a leadási időt is.
