### ISSUE TITLE
Áramlástan feladat megoldásom 3/5A

### ISSUE THREAD

**Issue by korontospetra** [PE-MK-JAKI-H/MAFGY#19]
Tisztelt Tanár Úr! 
Legyen szíves megnézni,hogy jó-e a számolásom.
![Áramlástan feladatom](https://user-images.githubusercontent.com/63107246/80108550-b659d180-857c-11ea-8e98-793c97599a81.jpeg)

**Comment by Szalay** [comment]
A megoldás rendben van, egy ponton javasolnék módosítást: a vektor értékű erőegyenletből kellene indulni, ezt akarod megoldani F_T-re, ezért számolod ki a többi erőt külön-külön. 

Az ábrák is rendben vannak.
