### ISSUE TITLE
Megoldás

### ISSUE THREAD

**Issue by Cindy9811** [PE-MK-JAKI-H/MAFGY#2]
![IMG_20200405_163127](https://user-images.githubusercontent.com/63102652/79067600-c80bc100-7cc0-11ea-9b57-9a30351f2776.jpg)

Helyes a feladat megoldása?

**Comment by Szalay** [comment]
Elvi hiba van a számításban. A cső forog, emiatt forgó erőtérben történik az áramlás, és a Bernoulli-egyenletet hozzá kell igazítani az erőtérhez (az áramlástan jegyzetben az 5.3.3. harmadik pontja). A víz a csőben már áramlik, emiatt az A/2 pont rossz helyen van. Fölösleges betűvel és számmal is jelölni a vizsgált pontokat, viszont számozásnál a kezdőpontot célszerű 1-essel jelölni.

Az elektronikus változatban a főbb lépésekhez kell majd írni magyarázatot.

**Comment by Cindy9811** [comment]
Kedves Tanár Úr!
Nem értem, hogyan kéne a Bernoulli-egyenletet hozzá igazítani az erőtérhez?
Így csináltam meg Latexben.
![1](https://user-images.githubusercontent.com/63102652/79563303-d71db500-80ac-11ea-9c37-4aec07de3dd0.jpg)
![1_2_](https://user-images.githubusercontent.com/63102652/79563306-da18a580-80ac-11ea-9777-d5976c185f06.jpg)

**Comment by Cindy9811** [comment]
Illetve ehhez a feladathoz lenne még egy kérdésem.
A múltkor azt tetszett írni, hogy a l/s-ot úgy írjam be: \si{\liter\per\second}, amit meg is tettem, viszont lefordítva az úgy néz ki: L/s.
Ha pedig \si{\Liter\per\second} írok be akkor kis l-el fordítja le, de az meg úgy néz ki,mint egy 1-es.
Melyik legyen akkor?
Én még mindig maradnék az eredeti kézzel írott l-nél ($\ell$), mert akkor meglehetne különböztetni.

Válaszát előre is köszönöm!

**Comment by Szalay** [comment]
A forgó erőteres problémánál az (5.16)-os egyenletet kell alapul venni a helyzeti energiához. A Bernoulli-egyenletben nem gz lesz a helyzet ienergia, hanem 1/2(\omega^2 r^2) + gz.

A vektor jelölés néhol hibás, a nyíl ne lógjon az alsóindexek fölé! A skalárszorzatot jelöld ponttal, \cdot. 

A liter legyen nagy L, az SI hivatalosan ezt ajánlja.

**Comment by Cindy9811** [comment]
Kedves Tanár Úr!

Köszönöm szépen, holnap javítom is.
Igen, a skalárszorzatot már én is észre vettem,az már javítva is van.
