### ISSUE TITLE
Elkészíttettem a feladatomat (YIYL9B)

### ISSUE THREAD

**Issue by toti9058** [PE-MK-JAKI-H/MAFGY#20]
Tisztelt tanár úr! 

Elkészültem a feladatommal (MAFGY-K3/4), igen már régebben kész volt csak még nem kaptam visszaigazolást, hogy megfelel-e így a feladatom vagy még foglalkoznom kell-e vele? 
Illetve az érdekelne, hogy jelenlegi formájában mennyire elfogadható? 

Tisztelettel:
Tóth Ákos (YIYL9B) 
Gépészmérnök Bsc.

**Comment by Szalay** [comment]
Az utolsó commitban csak a PDF van benne, a forrás nincs. Mindenesetre néhány hibát leírok, amit a PDF-ben látok:
1) A sűrűséget q_v-vel jelölöd az adatok között, \varrho_V legyen, és 1000 legyen az értéke!
2) A (3.4)-es egyenletben a nyíl csak J-ken legyen, az alsóindexekre ne lógjon rá.
3) Az x_1 azért nem megoldás, mert a négyzetgyöke lenne a sebesség, és a sebesség nem lehet komplex szám.

**Comment by toti9058** [comment]
Azóta töltöttem fel még egyet abban én látom a forrást.

**Comment by Szalay** [comment]
Igen, ez most rendben van. Átnézem.

**Comment by toti9058** [comment]
A (3.16)-nál azért raktam kívülre mert akkor az annak a sornak a többi részét külön sorba rakja és máshogy nem jöttem rá, hogyan tudom oda rakni. Ebben az esetben hogyan legyen?

A többit azt megcsináltam és mindjárt frissítem. A legvégén írtad, hogy kéne 1-2 helyen magyarázni a számolást az érthetőség kedvéért ezek melyik sorok és mit kéne oda írjak?

**Comment by Szalay** [comment]
A (3.16)-hoz: 
![image](https://user-images.githubusercontent.com/8204804/80978442-58ec3d00-8e26-11ea-889b-a1609b858ef9.png)

**Comment by Szalay** [comment]
Jelen pillanatban még nincs javítva atöbbi hiba sem.

**Comment by toti9058** [comment]
![image](https://user-images.githubusercontent.com/63107520/80979200-55a58100-8e27-11ea-95e7-c50f1b6292c5.png)
![image](https://user-images.githubusercontent.com/63107520/80979277-6b1aab00-8e27-11ea-912f-6a2ebef3306a.png)
![image](https://user-images.githubusercontent.com/63107520/80979304-74a41300-8e27-11ea-9211-e46cf96c844b.png)
Nálam ezek láthatóak.

**Comment by Szalay** [comment]
Megnéztem újra, és kihúztam a listáról, amit javítottál, de maradt néhány pont:
![image](https://user-images.githubusercontent.com/8204804/80989376-26960c00-8e35-11ea-8ab9-c020fa50ce9a.png)

**Comment by toti9058** [comment]
Kijavítottam a hibákat amiket kért, néhány hiba amit emített, hogy még nincs kész azok ki voltak javítva csak nem látszottak a képen. Meg remélem most már látszik, hogy felküldtem. 
Egyedül az nincs megcsinálva, hogy 2-3 soronként írjak magyarázatot mert nem igazán tudom, hogy mit írjak. 
Azt szeretném még kérdezni, hogy jelenlegi formályában a beadandóm hányast érne, ha le szeretném adni?

**Comment by Szalay** [comment]
Lepontoztam, az eredményt megtalálod a Google-táblázatban.
