### ISSUE TITLE
[S050X8] - Ellenőrzésre adás

### ISSUE THREAD

**Issue by acomyss** [PE-MK-JAKI-H/MAFGY#21]
Tisztelt Tanár Úr!

Feltöltöttem a javításokat, kérem ellenőrizze őket!

Tisztelettel,
Pesti Andrea Zita

**Comment by Szalay** [comment]
Átnéztem, a következők javítandók:
1) A táblázatban a szak Biomérnök alapszak legyen.
2) Az ábra kicsit zsúfolt, de elvi hiba nincs rajt. Javítandó egyedül a középvonalak szaggatása: `\draw[... dash pattern={on 8mm off 1mm on 0.5mm off 1mm} ...] ...`
3) Az (5.1)-es egyenletben vagy vedd külön oldalra az 1-es és 2-es ponthoz tartozó mennyiségeket, vagy a 0 kapja meg a neki járó mértékegységet! Ez az (5.3)-ra ia igaz. A jobbik megoldás a szénbontás lenne.
4) Az (5.1) után le kellene írni, hogy a legnagyobb gyorsulású állapotot vizsgálod, ami a kulisszás hajtómű forgó és a dugattyú lengő mozgása miatt egyben a 0 m/s áramlási sebességű pillanat.
5) Az (5.2)-esben az első integrál utáni 0 mértékegysége rossz.
6) Az (5.4)-től maradt az egyenletekben néhány fölösleges pont. 
7) Az utolsó egynelet vége `...\SI{0,92}{\per\second} = \SI{55,2}{\per\minute}` legyen!

A legvégére egy egymondatos magyarázat még kerüljön!

**Comment by Szalay** [comment]
Lepontoztam a beadandód, az eredményt megtalálod a Google-táblázatban.
