### ISSUE TITLE
Javított verzió (Leadásra kész)

### ISSUE THREAD

**Issue by CsHunor** [PE-MK-JAKI-H/MAFGY#22]
Tisztelt Tanár Úr! 

1. Minden apróbb hibát kijavítottam, amit Ön megjegyzésbe hozzáfűzött (kivétel néhány helyen a betűk közti szorzásjelet, ami szerintem, úgy esztétikus, ha alkalmazzuk a szorzásjelet máskülönben összefolynak a betűk) 
2. Elégedetlen volt az ábrákkal! Újrarajzoltam az Ön által megosztott ábrázolás technika szerint (generált kódot töröltem) ! 
3. Érdeklődni szeretnék, hogy a javított verzió ellenőrzés után, milyen osztályzatot tudna érte adni? 

Tisztelettel:
Cseresznyés Hunor
Biomérnök Bsc.

**Comment by Szalay** [comment]
Átnéztem, és a teljesség igényével írtam össze a javítandó dolgokat. Nagy hibák már nincsenek, de sok apróságot ki kell még javítani.
1/16:
1) Az első sor végén a "ha" szó fölöslegesen egyenlet.
2) A h legyen egyszerűen 1 m, az "egész nulla" semmit nem tesz hozzá.
3) Amikor a D méretet megadod, akkor nem kell átmérőjel (ami egyébként a \diameter, nem a \varnothing). Az átmérőjel csak az ábrán kell.
4) A sűrűséget is az SI paranccsal add meg. Ha ettől esetleg szétcsúszik az első oldal, akkor megadott méreteket rendezd egy sorba.
5) Az ábra sokkal jobb, de maradt néhány javítandó részlet, például a képfelirat. 
6) A vastag vonalakat az `ultra thick` vastagsággal rajzold. A csatlakozó vonalszakaszokat össze lehet vonni, ez kevesebb és rövidebb parancsot eredményez, és például le lehet krekíteni a sarkokat:
`\draw [ultra thick, rounded corners=1mm] (-3,0) -- (-3,-2.5) -- (3,-2.5) -- (3,0);`
7) A középvonal szaggatását ezzel mintával csináld:
`\draw [dash pattern={on 8mm off 1mm on 0.5mm off 1mm}] ...`
8) A vízfelszíneket jelölni kellene egy-egy háromszöggel.
9) A méreteket így csináld (a kapcsos zárójelek fölöslegesek, a méreteket lehetőség szerint kívülre kell tenni, a függőleges méretek a jobb oldalra tenni, balra forgatva:
`\pgflength[xa=2, ya=-1.5, xb=2, yb=-0.5, blim=0]{$h$};`
`\pgflength[xa=-2, ya=0.5, xb=2, yb=0.5, ra=-0.65]{${\diameter D}$};`
10) A megoldás első bekezdében az "amely" előtt hiáyzik a szóköz.
11) Az (1.2) és (1.) egyenletben is az \SI-vel legyenek szedve a mértékegységek. Később egyszer a bar és egyszer a newton sima szöveg.

1/18:
1) Az l = 2 m után fölösleges szóköz van.
2) A vastag vonalak itt is ultra thickek legyenek, de a dA körüli vonalak ne legyenek vastagok.
3) A méretezésben több hiba is van. A \pgflength-hez írok segdéletet a Moodle-be, és az alapján ki kellene majd javítani.
4) A megoldásban a newtonok \SI-vel legyenek.
5) Hiányzó szóköz a "Ha" előtt.
6) 2-3-nál több egymást követő egyenlet ne legyen. Ilyen helyeken egy magyarázó mondat legyen beszúrva.
7) Túl sok a pont, az utolsó egyenletben még a mínusz jel mellé is tettél.

Ha ezeket mind kijavítod, akkor nem csak elfogadható, hanem 70-80 % körüli lesz a beadandó.

**Comment by Szalay** [comment]
Úgy tűnik legutóbb a két sárgával kiemelt 25 %-os rész elkerülte a figyelmem.
