### ISSUE TITLE
Feladatok ábrákkal

### ISSUE THREAD

**Issue by Cindy9811** [PE-MK-JAKI-H/MAFGY#25]
Kedves Tanár Úr!

Feltöltöttem a feladataimat ábrákkal együtt, megtetszik majd nézni?

Előre is köszönöm szépen!
Üdvözlettel,
Talpai Szindarella

**Comment by Szalay** [comment]
**1/21**
A szövegben és az ábrán is vannak apróbb pontatlanságok, de alapvetően rendben van, úgyhogy pontoztam. Az eredményt megtalálod a Google-táblázatban. Ha javítanál rajt, akkor ezeket nézd meg:
1) Szabályos méretezés az ábrán.
2) Nyomatékegyenlet egyértelműen felírva.
3) A körvonalak `ultra thick` vastagok legyenek. 

**2/13**
Ezzel több gond van, a következőket javítani kell:
1) A könyökcső könyöke legyen állandó ámérőjű, és az r legyen nagyobb mint h (ahogy az adatok között is nagyobb)! A körvonalak itt is `ultra thick` vastagok legyenek. 
2) Az áramvonal kezdete legyen az 1-es pont és a vége a 2-es, és egy vastag színes vonalla legyen megjelölve az ábrán.
3) Az áramvonal legyen megjelölve és a külső felszínről induljon!
4) A megoldás még mindig nem jó, és nem csak azért, mert a térfogatáram hiányzik a végén. Nyomáskülönséget nem számolhatsz hidrostatikai módszerrel, mert áramlik a víz. Ehelyett a helyzeti energiát kell felírni forgó rendszerben. A (2.6)-os Bernoulli-egyenlet jó, annak kell kijönni az előtte lévő a részből azzal a kiegészítéssel, hogy az r_1 melletti omega = 0, hiszen a csöbön kívül nem forog a víz. A példatárban lévő eredmény egyébként jó, ha végigcsinálod a számítást, akkor abból látod, hogy sikerült-e jól megoldani a feladatot.

**Comment by Cindy9811** [comment]
Kedves Tanár Úr!
Köszönöm a megjegyzéseket. 
A csatolt kép alapján kijött az eredmény a 2/13 as feladatnál, illetve a nyomáskülönbséget is javítottam.Egy kicsi eltérés van a feladatgyűjtemény és az én megoldásom között. Nekem kereken 6 L/s-ra jött ki, a példatárban 5,9 L/s van, az nem baj?
A körvonalakat is megvastagítottam, ha időm engedi a többit is igyekszem javítani!

**Comment by Cindy9811** [comment]
Kedves Tanár Úr!

Feltöltöttem, az újabbat, pár javítással még, azt hiszem még egy ellenőrzésem van hátra. Megtetszik majd nézni a javításokat? Az ábra méretezését még nem javítottam.

Előre is köszönöm!

**Comment by Szalay** [comment]
**2/13**
1) A könyökrész még mindig nem állandó ámérőjű, és ami még nagyobb hiba, az az, hogy nem a függőleges rész középvonala körül forog. 
2) Az ábrán az áramvonal rossz helyen van, és rossz irányba tart. Az áramvonalat a csövön kívülről, a vízfelszínről kellene indítani, és onnan felvinni a cső szájához.
3) A nyomáskülönbséges részre egyáltalán nincs szükség, az előbbi pontból kiderül, hogy az áramvonal elején és végén is légköri nyomás mérhető. És a számítás csak hidrostatikai esetben lenne helyes, de itt áramlik a folyadék.
4) A két omega lehetne omega_1 és omega_2.
5) A 2.7-es és a 2.8-as egyenletekben előjel hiba van.
6) Az áramlási sebesség értéke 8,2 m/s körüli, a térfogatáram valamivel kisebb, mint 6 L/s.

A fentiektől függetlenül pontoztam a feladatokat, az eredményt megtalálod a Google-táblázatban. Ha a fentieket javítod, akkor újra megnézem a beadandót.

**Comment by Cindy9811** [comment]
Kedves Tanár Úr,

megnéztem a táblázatot, és így akkor összesen 74,25 pontos lett a két feladat.
Elfogadom ezt a pontszámot, köszönöm szépen!
Esetleg majd egy útmutatót tudna írni, hogy hogyan kell véglegesen feltölteni? 

Előre is köszönöm!,
Üdv,
Szindarella

**Comment by Szalay** [comment]
Már nem kell csinálnod semmit.
