### ISSUE TITLE
Javítás

### ISSUE THREAD

**Issue by dominiksarvari** [PE-MK-JAKI-H/MAFGY#27]
Tisztelt Tanár Úr!

Kijavítottam a hibákat a Veszteségmentes csőáramok rész 2/1-ben, és újragondoltam a rossz feladatot. Ha ideje engedi kérem nézze meg a kijavított példákat.

Saját hülyeségem miatt problémám akadt a feltöltéssel, de szerencsére sikerült megoldani, remélem minden fáj a helyére került.

Segítségét és megértését előre köszönöm!

Tisztelettel: Sárvári Dominik Levente

**Comment by Szalay** [comment]
Átnéztem és pontoztam is, az eredményt megtalálod a Google-táblázatban. Nem zöld, mert még van javítási lehetőséged, és lenne is mit javítani. Ha szeretnél még javíytani a beadandón, akkor írok egy listát.

**Comment by dominiksarvari** [comment]
Sajnos nem jelenik meg a pont a Google-táblázatban.

**Comment by Szalay** [comment]
A feladat mellé írtam.

**Comment by dominiksarvari** [comment]
Már látom, köszönöm szépen! Számomra ez megfelel, van még valami teendő a leadással?

**Comment by Szalay** [comment]
Nem volt más teendő.
