### ISSUE TITLE
H1.5. feladat számolás és ábra

### ISSUE THREAD

**Issue by gerbovitsditta** [PE-MK-JAKI-H/MAFGY#28]
Tisztelt Tanár Úr!
Feltöltöttem a feladat számolását és az U cső ábráját, ha ideje engedi megnézné esetleg? 
Köszönettel:
Gerbovits Ditta

**Comment by Szalay** [comment]
Megnéztem, az első probléma, amit látok, az az, hogy a forrásfájlokat nem töltötted fel, csak a lefordított pdf-et, emiatt nem tudom a forrásban megjelölni a hibákat. Emiatt csaka a jelentősebbeket gyűjtöttem össze:

1) Az ábrán a vonalvastagságok és a vonatípusok feleljenek meg a műszaki rajzban szokásosnak!
2) Az egyenletekben sok a fölösleges pont, viszont az egyetlen helyen, ahol kellene legyen pont ott nincs :) Ez az 1.3-ban a skalárszorzat. Ugyanitt az integrálási határok hiányoznak az egyik integrálról.
3) Az indexekben lévő törteket a `\frac` paranccsal hozd létre.
4) A forgó állapotról készítendő ábra hiányzik.
5) A számítás mellé egy-egy ponton még szükség lenne magyarázatra.

A számítás menete alapvetően rendben van, és az eredmények is jók.
