### ISSUE TITLE
H1.8. feladat ábrával

### ISSUE THREAD

**Issue by Oroszagi98** [PE-MK-JAKI-H/MAFGY#29]
Tisztelt Tanár Úr!
Feltöltöttem a feladatomat, ha ideje engedi, kérem nézze meg.

**Comment by Szalay** [comment]
A feladatmegoldás menet és a számértékek rendben vannak, de sok az apró hiba, aminek a nagyrésze a fölösleges $ jelek miatt van. A megjegyzéseket itt megtalálod: https://github.com/PE-MK-JAKI-H/MAFGY/commit/a761e0a3a29b0a3acad16a7e19e7bea7656fa015

Az egyenletfajtákhoz a Moodle-ben van leírás. Amit ott talán nem írtma le egyértelműen, hogy a különböző fajta egyenleteket áltlaában nem lehet keverni.
