### ISSUE TITLE
Megoldás-2

### ISSUE THREAD

**Issue by Cindy9811** [PE-MK-JAKI-H/MAFGY#3]
![IMG_20200405_163119](https://user-images.githubusercontent.com/63102652/79067639-233db380-7cc1-11ea-94f4-a510db5143df.jpg)

Helyes a feladat megoldás?

**Comment by Szalay** [comment]
A megoldási menet és a számértékek alapvetően jók, csak apróbb kifogásolható pontokat találtam: a p nyomás átlagnyomás a kifolyónyílásban, a p_0 azért tűnik el, mert kívülről levegő is nyomja az elzáró fedelet, és a végleges változatban a mértékegységek ne maradjanak le a részeredmények mellől sem. És a főbb lépésekhez kellene majd írni magyarázatot is.
