### ISSUE TITLE
áramlástan feladat ellenőrzése

### ISSUE THREAD

**Issue by qiseel** [PE-MK-JAKI-H/MAFGY#30]
Jó napot kívánok!

A Latex-ban szerkesztett feladatomat szeretném leellenőriztetni, az ábrától egy kicsit eltértem mint ami a feladatgyűjteményben mert szerintem így jobban el lehet magyarázni. 

Köszönöm!

Biró Géza Konrád
qiseel

**Comment by Szalay** [comment]
Átnéztem, a megjegyzéseket itt megtalálod: https://github.com/PE-MK-JAKI-H/MAFGY/commit/b0e512bad59afde7bfe27d7377322f90bb34804a

Az ábránál az eltérés nem jelentős, és elfogadható. Az utántöltést kellene azért jelölni, mert annak van jelentősége.

Még nem pontoztam, mert még sok a hiba.
