### ISSUE TITLE
Segítség kérés és előzetes ellenőrzésre adás (CVQYX8)

### ISSUE THREAD

**Issue by acomyss** [PE-MK-JAKI-H/MAFGY#31]
Tisztelt Tanár Úr,

elkészítettem egy előzetes verziót a beadandóból, azonban a kódban a figure3 és 4-ben kérem a segítségét a megjelölt részen!
Előre is nagyon szépen köszönöm!

Tisztelettel,
Hotváth János
(CVQYX8)

**Comment by Szalay** [comment]
Itt mi történt?

**Comment by HorvathJanos97** [comment]
Tisztelt Tanár Úr,

Sajnos nagyon rossz az internet elérés nálunk, többször megszakadt a
feladatmegoldás feltöltése közben is, emiatt kértem meg Andit, hogy legyen
szíves ellenőrizni, hogy a kódom elérhető-e a githubon. Azért, hogy Ön
minél előbb el tudja kezdeni az ellenőrzést, megkértem őt, hogy hozza létre
nekem az issue-t, ezzel is időt megtakarítva. Emiatt ő a létrehozó, és én
külön vagyok hozzárendelve általa.

Tisztelettel: Horváth János

Szalay <notifications@github.com> ezt írta (időpont: 2020. máj. 13., Sze,
15:21):

**Comment by Szalay** [comment]
Rendben, értem a helyzetet.

A feladatot átnéztem és pontoztam is, az eredményt a Google-táblázatban megtalálod.

**Comment by HorvathJanos97** [comment]
Tisztelt Tanár Úr,

Megtekintettem a Google-táblázatban a feladatomra kapott értékelést.
Az lenne ezzel kapcsolatban a kérdésem, hogy ez az eredmény még javítható a
félév során, vagy ez már a végleges eredményem és jelentkezhetek a
következő vizsga időpontra, hogy Ön beírhassa az érdemjegyem? Amennyiben
még javítható, a beadandó mely részei szorulnak javításra, illetve mivel
tudnék még pontot szerezni a jobb jegy eléréséhez?

Tisztelettel: Horváth János (CVQYX8)

Szalay <notifications@github.com> ezt írta (időpont: 2020. máj. 27., Sze,
12:59):
