### ISSUE TITLE
áramlástan feladat ellenőrzés

### ISSUE THREAD

**Issue by polzsofi** [PE-MK-JAKI-H/MAFGY#33]
Tisztelt Tanár Úr!  
Még korábban feltöltöttem a kész feladataimat ábrákkal együtt ellenőrzésre. Kérem, szíveskedjen megnézni őket! 
Köszönettel: Polgár Zsófia, OI7WSG

**Comment by Szalay** [comment]
Átnéztem és pontoztam, de nem jeelnlegi, hanem a forrás mellé írt a rövidebb megjegyzések javítása utáni állapotra, azaz az eredmény a javítás után él. Ha ezen felül még szeretnél javítani, akkor írok egy listát a teendőkről.

A következő feltöltésnél a gyökérdokumentum és a lefordított PDF is legyen feltöltve.

**Comment by Szalay** [comment]
Ellenőrizve a felaatválasztást azt láttam, hogy igazából 125 pontnyi feladatot választottál, de a Venturi-mérős feladat második 25 pontos részét nem csináltad meg. Ez nem a legjobb, de most már maradhat így.

**Comment by polzsofi** [comment]
Tisztelt Tanár Úr!

Még a feladatválasztáskor írtam Önnek emailt a feladatok miatt. Úgy állapodtunk meg, hogy a Venturi-mérős feladatnak csak a 75 pontos részét kell megcsinálnom, mert akkorra a jégtáblás feladatom már megvolt. 
Már javítom a hibákat, jó lesz azaz eredmény.  

Köszönettel: Polgár  Zsófia

**Comment by polzsofi** [comment]
Tisztelt Tanár Úr! 

Megnéztem újra a feladat pontozását. Érdeklődni szeretnék, hogy min kellene még változtatnom illetve javítanom a beadandó feladatban a korábban megírtakon kívül, hogy 70% felett legyen az eredményem?  Láttam, hogy nem sok választ el tőle. 
Válaszát előre is köszönöm! 

Üdvözlettel: Polgár Zsófia

**Comment by Szalay** [comment]
Megnézem újra, a következőkkel lehetne még javítani a beadandón:
1) A feltöltésből ne maradjon ki az MAFGY.tex és az MAFGY.pdf.
2) A feladatok végén legyen egy `\pagebreak` parancs, közben nem kell.
3) A sűrűség jele `\varrho` legyen!
4) A függőlege közök (\vspace) nem kellenek.
5) A mértékegységek ne maradjanak le! A térfigatáram mértékegysége hibás. A köb a \cubed.
6) A szövegben vanank apróbb elírások, furcsa fogalmazás, ezekre figyelj!

A 2/3-as ábráján:
1) Ki kellene emelni a vizsgált áramvonalat. A többiektől ultra thick vastag, kék, mid arrow-val készített nyilat kértem.
2) A keresztmetszeteket az ármétőkhöz hasonlőan kelleen megjelölni.
3) A végeken a cikkcakkos vonalakat a vastag körvonalak végeihez kellene igazítani.
4) A középvonal szaggatási mintája `dash pattern={on 8mm off 1mm on 0.5mm off 1mm}` legyen, és maradjon fekete!
5) Az A_2-nél kettes alsóindex.

Arra már nem emlékeztem, hogy a feladválasztást korábban rendeztük.

**Comment by polzsofi** [comment]
Tisztelt Tanár Úr!

Köszönöm szépen, igyekszem javítani!

Üdvözlettel: Polgár Zsófia

Szalay <notifications@github.com> ezt írta (időpont: 2020. máj. 16., Szo
15:24):

**Comment by Szalay** [comment]
Ezt az issue-t lezártam, mert nyitottál egy újat.
