### ISSUE TITLE
Feladat ellenőrzés

### ISSUE THREAD

**Issue by SzalaiViki** [PE-MK-JAKI-H/MAFGY#34]
Tisztelt Tanár Úr!

Feltöltöttem az ellenőrzésre kész feladatomat. 
Amennyiben ideje engedi, kérem legyen szíves ellenőrizni nekem.

Segítségét előre is köszönöm!

Üdvözlettel:

Szalai Viktória

**Comment by SzalaiViki** [comment]
Köszönöm szépen!
Érdeklődni szeretnék, hogy ez így hány pont lenne?

**Comment by Szalay** [comment]
Túl sok a hiba, ki kell javítani.

**Comment by SzalaiViki** [comment]
Tisztelt Tanár Úr!
Feltöltöttem a végleges változatot, javítottam a hibákat. 
Legyen szíves nekem megnézni. 
Válaszát előre is köszönöm!

**Comment by Szalay** [comment]
Átnéztem és pontoztam, az eredményt megtalálod a Google-táblázatban.

**Comment by SzalaiViki** [comment]
Koszonom szepen!
