### ISSUE TITLE
H1./5. feladat ellenőrzés

### ISSUE THREAD

**Issue by gerbovitsditta** [PE-MK-JAKI-H/MAFGY#36]
Tisztelt Tanár Úr!
Ha minden igaz feltöltöttem a tex fájlt is, a vonalvastagságokat javítottam és megpróbáltam még pár mondatban leírni a feladat lényegét. A rajzon fel van tüntetve a nyugalmi állapot és a forgás közbeni folyadékszint is. 
Ha ideje engedi legyen kedves leellenőrizni.
Köszönettel:
Gerbovits Ditta

**Comment by Szalay** [comment]
Megnéztem, a javítandó hibákat megjelöltem itt: https://github.com/PE-MK-JAKI-H/MAFGY/commit/2bc9853dccd7a39fcb6c3be210ca0b420075434d

A legfontosabb probléma, hogy a feladat csak 75 pont, és ebből 25 a forgó helyzet ábrája, amihez hozzá tartozik a potenciálfelszínek és a forgási paraboloid felszín megrajzolása is.

**Comment by gerbovitsditta** [comment]
Kedves Tanár Úr!
Ha esetleg bevállalnék még feladatot úgy teljesíthető lenne megajánlott jeggyel a tárgy? 
A feladathoz kapcsolódóan pedig tudna esetleg példát mutatni, hogy hogyan kellene kinézni az ábrának? 
Előre is köszönöm a választ!

**Comment by Szalay** [comment]
1) Teljesíthető így is, de ugye így legfeljebb 75 %-os eredményt tudsz elérni.
2) Még egy 25 pontos feladat szabad, a 4/4-es.

A rajzon a cső átmérőjét csökkenteném úgy felére, és 3-4 potenciálfelszínt megjelölnék, úgy, hogy az egyik éppen a kialakuló felszínnel essen egybe.
![image](https://user-images.githubusercontent.com/8204804/83329235-a1154880-a288-11ea-924f-1d627db3231a.png)
