### ISSUE TITLE
3/10-es feladat 

### ISSUE THREAD

**Issue by qiseel** [PE-MK-JAKI-H/MAFGY#37]
Jó napot kívánok!

Feltöltöttem a feladatomat újbóli ellenőrzésre, legyen szíves nézze át nekem, és meg tudná nekem majd írni hogy kb mennyi pont lenne így?

Köszönöm!

Biró Géza 
qiseel

**Comment by qiseel** [comment]
Jó napot kívánok!

Mai nap (05.17.) folyamán újból feltöltöttem mert láttam benne hibákat meg egy két dolgot javítottam , majd legyen szíves a mai verziót nézze meg, hogy mit kéne javítani és legyen szíves azt is megírni hogy körülbelül mennyi pontot érne.

köszönöm!
További szép napot!

Biró Géza Konrád
qiseel

**Comment by Szalay** [comment]
Átnáztem, a javítandó hibákat megjelöltem itt: https://github.com/PE-MK-JAKI-H/MAFGY/commit/648e164bcd5a2ac50d122d8d3f3004909e1e553e

A Google-táblázatban értékeltem is, de a pontszám a javítás után él.

Újabb issue-t nem kell nyitni, elég itt jeelzni, hogy ha javítottad.

**Comment by qiseel** [comment]
Rendben és köszönöm , a hétvégén javítom is a hibákat !

**Comment by qiseel** [comment]
Jó napot kívánok !

Javítottam a hibákat amiket tudtam ott a vektoros résznél nem vagyok benne biztos hogy jó-e amit csináltam , úgy csináltam ahogy nekem a kidolgozásban volt de akkor lehet az a rossz :) 

Üdvözlettel:
Bíró Géza Konrád

**Comment by Szalay** [comment]
A beadandót véglegesnek tekintem, a 87 %-os eredmény él, és jelest ér. Vizsgára jelentkezni ne felejts el!

**Comment by qiseel** [comment]
Köszönöm !!!! Keddre fel is vettem !
