### ISSUE TITLE
H1.8. feladat javítása

### ISSUE THREAD

**Issue by Oroszagi98** [PE-MK-JAKI-H/MAFGY#40]
Tisztelt Tanár Úr! 
Próbáltam kijavítani  a hibáimat. Ha ideje engedi,kérem nézze meg.

**Comment by Szalay** [comment]
Átnéztem és pontoztam a jelenlegi állapot alapján, az eredményt megtalálod a Google-táblázatban. Ha szeretnél javítani a beadandón, akkor írok egy listát a hiányosságokról.

Kerestem az MHFGY 7/5-öst is, de úgy tűnik, azt még nem csináltad me.

**Comment by Oroszagi98** [comment]
Tisztelt Tanár Úr! A feladat pontját nem látom a táblázatban. ( Az MHFGY 7/5-öst még nem csináltam meg.) A H1.8. feladatra kapott pontomat be tudná írni?

**Comment by Szalay** [comment]
Az 1/8-as eredménye bent van a táblázatban.
