### ISSUE TITLE
javítás, kész feladatok

### ISSUE THREAD

**Issue by polzsofi** [PE-MK-JAKI-H/MAFGY#41]
Tisztelt Tanár Úr!

Kijavítottam a megbeszélt hibákat és feltöltöttem értékelésre a végleges feladatokat!  

Üdvözlettel: Polgár Zsófia

**Comment by Szalay** [comment]
Átnéztem és pontoztam, az eredményt megtalálod a Google-táblázatban.

**Comment by polzsofi** [comment]
Tisztelt Tanár Úr!

Köszönöm szépen, örülök :) !

Üdvözlettel: Polgár Zsófia

Szalay <notifications@github.com> ezt írta (időpont: 2020. máj. 30., Szo,
17:11):
