### ISSUE TITLE
Ellenőrzés

### ISSUE THREAD

**Issue by lauravarga0128** [PE-MK-JAKI-H/MAFGY#42]
Tisztelt Tanár Úr! Szeretném ellenőriztetni a munkám, DTVOM1 Biomérnök Alapaszakos hallgató.

**Comment by Szalay** [comment]
Átnéztem és pontoztam, az eredményt megtalálod a Google-táblázatban.

Nem tökéletes, de mivel a jegyen nem változtatna, ezért nem javíttatom ki a hibákat.

**Comment by lauravarga0128** [comment]
Nagyon szépen köszönöm nekem ez a pontszám teljesen megfelelő és nagyon
örülök neki!

Üdvözlettel:

Varga Laura

Szalay <notifications@github.com> (időpont: 2020. máj. 30., Szo, 17:23) ezt
írta:
