### ISSUE TITLE
H3/12 feladat

### ISSUE THREAD

**Issue by BagoTimi** [PE-MK-JAKI-H/MAFGY#43]
Tisztelt Tanár Úr!

H3/12. feladatot elkészítettem és feltöltöttem. Szeretném kérni, hogy ellenőrizze.

Köszönettel:
Bagó Tímea
(UHIK3V)

**Comment by Szalay** [comment]
Átnéztem és pontoztam, az eredményt megtalálod a Google-táblázatban.

Nem tökéletes, de mivel a jegyen nem változtat, ezért nem javíttatom ki a hibákat.
