### ISSUE TITLE
2/12. feladat 

### ISSUE THREAD

**Issue by bdzsenifer** [PE-MK-JAKI-H/MAFGY#44]
Tisztelt Tanár Úr!
Elkészítettem az általam választott 2/12 (Dugattyú megengedhető legnagyobb gyorsulása) feladatot, majd fel is töltöttem azt.
Szeretném kérni, hogy ellenőrizze.

Tisztelettel: Bujdosó Dzsenifer

**Comment by Szalay** [comment]
Átnéztem és pontoztam a jelenlegi állapot alapján, az eredményt megtalálod a Google-táblázatban.

Ha szeretnél javítani a beadandón, akkor írok egy listát a hibákról.

**Comment by bdzsenifer** [comment]
Szívesen megpróbálnék javítani a feladatomon, ezért szeretném elkérni a listát a hibákról.

**Comment by Szalay** [comment]
Megjelöltem a javítandó dolgokat itt: https://github.com/PE-MK-JAKI-H/MAFGY/commit/bb54a0cdabe2796073cf7a30b9c5317fc3f6a8e5

Volt olyan hiba, ami többször is előfordult, de csak egyszer jelöltem meg.

**Comment by bdzsenifer** [comment]
Rendben, nagyon szépen köszönöm.
Igyekszem minél hamarabb kijavítani őket.

**Comment by bdzsenifer** [comment]
Elkészültem a javítással, remélem minden hibát sikerült kijavítanom.
https://github.com/PE-MK-JAKI-H/MAFGY/commit/a7f2f8d072cfed6d0b5b6cde12d6fc0a2947f33f

**Comment by Szalay** [comment]
Frissítettem a pontozást. Vizsgára ne felejts el jelentkezni!
