### ISSUE TITLE
K1.7A Feladat

### ISSUE THREAD

**Issue by zsombor0404** [PE-MK-JAKI-H/MAFGY#45]
Tisztelt Tanár úr! 

Mindkét feladatom a K1.7A-ba tartozik. A megoldásokat feltöltöttem ellenőrzésre, amennyiben úgy gondolja hogy megfelel, szeretném véglegesíteni.

GHWEWU

**Comment by Szalay** [comment]
Átnéztem és pontoztam a jelenlegi állapot alapján, az eredményt megtalálod a Google-táblázatban.

Ha szeretnél javítani a beadandón, akkor írok egy listát a hibákról.

**Comment by zsombor0404** [comment]
Kedves Tanár úr!

Szeretném  elfogadni a jelenlegi pontozást. Felveszem a legközelebbi vizsgaidőpontot. 

Üdvözlettel, Nagy Zsombor (GHWEWU)

**Comment by Szalay** [comment]
Rendben, felírtam.
