### ISSUE TITLE
H2/7 Tartály oldalán kiömlő vízsugár

### ISSUE THREAD

**Issue by DanielMolnar96** [PE-MK-JAKI-H/MAFGY#48]
Tisztelt Tanár Úr, szeretném ellenőrzésre adni a feladatmegoldásom. Emiatt létrehoztam egy pull requestet is.
Tisztelettel,
Molnár Dániel, RO8LFO

**Comment by Szalay** [comment]
Átnéztem és pontoztam a jelenlegi állapot alapján, az eredményt megtalálod a Google-táblázatban.

Ha szeretnél javítani a beadandón, akkor írok egy listát a hibákról.

**Comment by DanielMolnar96** [comment]
Ha jól számolom, akkor a 71 pont az 4-es, ez esetben elfogadnám! Amennyiben ideje engedi, csak a feladatmegoldás hibáit röviden össze tudná szedni? Csak kíváncsiságból. Köszönöm! 

Molnár Dániel, RO8LFO

**Comment by Szalay** [comment]
A jelölések elég vegyesek, v/V, kszí/dzeta, keveredik az energia veszteség és a veszteségmagasság. A megoldás a szöveg szintjén ésszerű felépítésű, de a formázás szintjén tagolatlan. Az ábrákon a vastag fekete sávokat nem értem, és van néhány kisebb rajzhiba. 

A jegyet beírtam a Neptunba.
