### ISSUE TITLE
Megoldás

### ISSUE THREAD

**Issue by PeczerFanni** [PE-MK-JAKI-H/MAFGY#5]
![92926213_1097110507313124_4220784461949698048_n](https://user-images.githubusercontent.com/63015351/79072098-77f02700-7cdf-11ea-99c1-0992a273a108.jpg)

Tisztelt Tanár úr!
A megtört lapra ható erő nevű feladatom megoldására a következőt kaptam. Szeretném megkérdezni, hogy ez így helyes-e, illetve ha helytelen akkor segítséget szeretnék kérni, hogy jó megoldást adhassak le. 

Köszönettel: Péczer Fanni

**Comment by Szalay** [comment]
1) A számítás menete és a számértékek alapvetően rendben vannak.
2) Az elektronikus változatban a főbb pontokhoz legyen szöveges magyarázat is.
3) Az ábrán az ellenőrző felület és a ható erők is jelenjenek meg, és ható erőkről legyen egy külön vektorábra, mert az egyenletek igazából abból írhatók fel.
4) Az első egyenletet indokolni kell, ennek egyik része a vektorábra leszm a másik viszotn a tömegáram feleződése.

**Comment by PeczerFanni** [comment]
Megpróbáltam az ábrába berajzolni az ellenőrző felületet, a hatóerőket, de a vektor ábra nem megy. Ez így helyes?

![92699367_915996638873022_2208909595957526528_n](https://user-images.githubusercontent.com/63015351/79075446-39646780-7cf3-11ea-8210-8d02da799ff9.jpg)

**Comment by Szalay** [comment]
Van, aki így veszi fel az ellenőrzőfelületet, hogy körbeveszi vele az egész vizsgált testet, és lehet így is csinálni, de szerintem célszerűbb összeszűkíteni, és csak a vízsugár érdekes részét belevenni. A csatolt ábrához hasonlóra gondolok. Emellet az erővektorokat is kétféleképpen lehet kezelni, és a célszerűbb választás a kifelé mutatá impulzuserő vektorok alkalmazása. És ezek vektorok, amit jelölni kell az ábrán is, és mivel "I" a lendület jele ugyanabban a témakörben, ezért jobb J-vel jelölni őket. A nyomás viszont nem vektormennyiség. A nyomóerők a vektorok.
![image](https://user-images.githubusercontent.com/8204804/79080050-0631d080-7d13-11ea-9029-3f60f111ae25.png)

**Comment by PeczerFanni** [comment]
Próbálkoztam tovább, most sem jó még? 
![utolsó](https://user-images.githubusercontent.com/63015351/79117242-e3db9980-7d8a-11ea-979f-65de5fcbba6e.jpg)

**Comment by PeczerFanni** [comment]
Közben rájöttem, hogy a tömegáramot a térfogatáramból kapom meg.
