### ISSUE TITLE
2/5. feladat 

### ISSUE THREAD

**Issue by hogyorkinga** [PE-MK-JAKI-H/MAFGY#51]
Tisztelt Tanár Úr!

Szeretném, ha ellenőrizné a feladatomat, amit az Áramlástan feladatgyűjteményből készítettem (2/5. feladat).
Köszönöm!

Tisztelettel:
Hogyor Kinga 
HQZ6FQ

**Comment by Szalay** [comment]
Ezt az issue-t lezártam, mert a másiknál válaszoltam.
