### ISSUE TITLE
K1/4A feladat kész

### ISSUE THREAD

**Issue by kunandras28** [PE-MK-JAKI-H/MAFGY#52]
Kedves Tanár Úr!

A két feladatom közül az egyiket megoldottam a 75 pontosat (K1/4A) és szeretném ha értékelné.
A másik feladatomat a későbbiekben feltöltöm!

Üdvözlettel Kun András (CL1Q4F)

**Comment by kunandras28** [comment]
Kedves Tanár Úr!

Elkészítettem és feltöltöttem mind a kettő feladatomat (K1/4, K2/8) és szeretném ha értékelné!

Üdv. Kun András (CL1Q4F)

**Comment by Szalay** [comment]
Átnéztem és pontoztam mindkét feladatot a jelenlegi állapot alapján, az eredményt megtalálod a Google-táblázatban.

Ha szeretnél javítani a beadandón, akkor írok egy listát a hibákról.

**Comment by kunandras28** [comment]
Kedves Tanár Úr!

Elszeretném fogadni a pontot, amit ajánlott a feladatomra a következő vizsgára (jun.2) pedig jelentkezek!

Köszönettel Kun András

**Comment by Szalay** [comment]
Rendben, felírtam.
