### ISSUE TITLE
5/2. feladat

### ISSUE THREAD

**Issue by hogyorkinga** [PE-MK-JAKI-H/MAFGY#53]
Tisztelt Tanár Úr!

Szeretném kérni az 5/2. feladatom (Billenőgyűrűs manométer) ellenőrzését.

Tisztelettel:
Hogyor Kinga
(HQZ6FQ)

**Comment by Szalay** [comment]
Átnéztem és pontoztam mindkét feladatod a jelenlegi állapot alapján, az eredményt megtalálod a Google-táblázatban.

Ha szeretnél javítani a beadandón, akkor írok egy listát a hibákról.

**Comment by hogyorkinga** [comment]
Köszönöm szépen! Van rá esély, hogy ha nem is tudom kijavítani az összes hibámat, akkor is javítani tudok a jegyen?

**Comment by Szalay** [comment]
A 75 pont 75 %-ot jelent. A következő szint 80 %-tól az ötös. Ahhoz elég jól ki kell javítani.

**Comment by hogyorkinga** [comment]
Rendben, akkor, ha elfogadom a jelenlegi pontszámot, jelentkeznem kell a legközelebbi vizsgára és van még valami további teendőm?

**Comment by Szalay** [comment]
A vizsgajelentkezésen kívül nincs más teendőd.
