### ISSUE TITLE
1/2A feladat

### ISSUE THREAD

**Issue by SturmReni** [PE-MK-JAKI-H/MAFGY#54]
Tisztelt Tanár úr!
Szeretném kérni az 1/2A feladat (Függőleges tengely körül forgó tartály) ellenőrzését.

Köszönöm,
Sturm Renáta (EQSJGB)

**Comment by Szalay** [comment]
Ezt az issue-t lezártam, mert a másik feladatodnál válaszoltam.

**Comment by Szalay** [comment]
Átnéztem és pontoztam mindkét feladatod a jelenlegi állapotuk alapján, az eredményt megtalálod a Google-táblázatban.

Ha szeretnél javítani rajtuk, akkor írok egy listát a hibákról. A legnagyobb hiányosság a 25 pontos nyomás-hely függvény volt, de sok apróbb hiba is maradt a megoldásokban.
