### ISSUE TITLE
mdpm86

### ISSUE THREAD

**Issue by fromhun** [PE-MK-JAKI-H/MAFGY#56]
Tisztelt Tanár Úr!

Feladatom végső formában fel van töltve, előző issue alapján ellenőrizve és javítva is van Ön által. Kérem annak pontszámát a Google táblázatban feltűntetni vagy nyugtázni annak elfogadását.

Köszönettel: Vasáros Mátyás

**Comment by Szalay** [comment]
A feladat elfogadható szinten van, pontoztam is az utolsó feltöltés alapján. Az eredményt megtalálod a Google-táblázatban.
