### ISSUE TITLE
H1/5. feladat javítva

### ISSUE THREAD

**Issue by gerbovitsditta** [PE-MK-JAKI-H/MAFGY#57]
Tisztelt Tanár Úr!
Javítottam a hibákat amiket megjelölt és megrajzoltam a forgás során létrejövő felszínt is.
Ha ideje engedi legyen kedves megnézni. 
Köszönettel:
Gerbovits Ditta

**Comment by Szalay** [comment]
Átnéztem, a pontozást megtalálod a Google-táblázatban.

A potenciálfelszíneket és a folyadékfelszíneket nem sikerült jól megcsinálni. A 4/4-es hiányzik.
