### ISSUE TITLE
Veszteségmentes csőáramlások

### ISSUE THREAD

**Issue by Rozsibence** [PE-MK-JAKI-H/MAFGY#58]
XGAP2Z

**Comment by Szalay** [comment]
A számítás menete rendben van, de beadandó kidolgozottsága kifejezetten hanyag. 
1) A feltöltött változat nem fordítható le.
![image](https://user-images.githubusercontent.com/8204804/84812446-b7ecc680-b00e-11ea-8077-78cc5ecaa37c.png)

2) Valamilyen problémát sikerült okozni a Git használata során, emiatt oda nem való sorok kerültek a beadandóba.
3) Bent maradt egy rész egy másik beadandóból.
![image](https://user-images.githubusercontent.com/8204804/84812536-d8b51c00-b00e-11ea-9cde-cf4c3124a504.png)

4) A jelölések nem követik a Moodle-ben leírtakat, és még csak nem is egységesek.
5) Szöveges magyarázatból nincs túl sok, ami pedig megvan, annak nem a címsorokban kellene lenni, hanem folyószövegben.
6) Az ábra nem követi a sem műszaki rajz szabályait, sem a feladat eredeti ábráját.

**Comment by Rozsibence** [comment]
Jó napot tanár úr!
Kijavítottam az ön által talált hibákat és feltöltöttem a végső verziómat!
Üdvözlettel: Rozsi Bence

**Comment by Szalay** [comment]
Átnéztem és pontoztam, az eredményt megtalálod a Google-táblázatban.
