### ISSUE TITLE
I3IHGZ Áramlástan K1/15-ös példa

### ISSUE THREAD

**Issue by Botyporus** [PE-MK-JAKI-H/MAFGY#59]
Elkészítettem a K1/15-ös áramlástan gyakorlati példát. I3IHGZ

**Comment by Szalay** [comment]
A nyomás-hely függvények hiányoznak, ami baj, mert a pontok fele arra jár. Ezen kívül viszont csak két appróbb javítani való van: a sűrűség `\varrho` legyen` , illetve egy egynondatos magyarázat azért kellene a számítás mellé. Ez utóbbit lehet a másik ábrához kötni, mivel igazából az ábra magyarázza meg a számítási összefüggést.
