### ISSUE TITLE
áramlástan 4/1

### ISSUE THREAD

**Issue by qiseel** [PE-MK-JAKI-H/MAFGY#6]
![áramlástan 41](https://user-images.githubusercontent.com/63043062/79073134-19c64280-7ce5-11ea-9c2e-91d1b6e13b04.jpg)

**Comment by qiseel** [comment]
Jó napot kívánok ! ennek a feladatnak így jó a megoldása?

**Comment by Szalay** [comment]
1) Ez csak a 25 pontig terjedő rész megoldása, de a síklapos ábra ehhez is kell (sebesség és csúsztató feszültség eloszlással).
2) A viszkozitás jele majd \eta legyen.
3) A derivált ebben az esetben teljes, de meg kellene magyarázni, hogy miért.
4) A számértékek rendben vannak.

**Comment by qiseel** [comment]
Rendben és köszönöm! az ábrát úgy tetszik érteni hogy a Latexban meg kell szerkeszteni? Az úgy kb mennyi pont lenne a 25-ből?

**Comment by Szalay** [comment]
A síklapos ábra 10 (a 25 40%-a). A Google táblázatban pedig bent vannak a feladat lehetséges bővítései.

**Comment by qiseel** [comment]
Rendben! még egy utolsó kérdés estére, láttam hogy egyes feladatok amelyek több részből állnak pl 75+25 és fekete keretbe kerültek az azt jelenti hogy akkor mindkét részt meg kell csinálni, az én esetemben 3/10-es feladatnál csak a 75 pontoshoz írtam magamat oda

**Comment by Szalay** [comment]
A fekete keret egy egyben választandó feladat összetartozó, de külön pontozott részeit jelenti.
