### ISSUE TITLE
3/8 Coanda-hatás

### ISSUE THREAD

**Issue by GroberAdel** [PE-MK-JAKI-H/MAFGY#60]
Tisztelt Tanár Úr! 
Elkezdtem csinálni a Coanda-hatás feladatot, kérem, legyen szíves ellenőrizni majd. A rajzok jók lesznek így, vagy mindenképpen koordináta-rendszerben kellenek?

Tisztelettel,
Grőber Adél

**Comment by Szalay** [comment]
A ajvítandó hibákat megjelöltem itt: https://github.com/PE-MK-JAKI-H/MAFGY/commit/3d6ad5434b701ec7799163f2c858d611a4f1a9ab

**Comment by GroberAdel** [comment]
Tisztelt Tanár Úr!

Amit tudtam, azt javítottam a beadandóban. 

Tisztelettel,
Grőber Adél

**Comment by Szalay** [comment]
Átnéztem és pontoztam, az eredményt megtalálod a Google-táblázatban.
