### ISSUE TITLE
MAFGY 3/11B  feladat ellenőrzése

### ISSUE THREAD

**Issue by KraniczAnna** [PE-MK-JAKI-H/MAFGY#61]
OCPVFM branch

**Comment by Szalay** [comment]
A számítás menetével is vannak gondok, és a beadandó kidolgozottsága elég hanyag.
1) A jelölések nem követik a Moodle-ben leírtakat, és még csak nem is egységesek.
2) Szöveges magyarázatok egyáltalán nincsenek. Legfeljebb két-három egyenlet lehet közvetlenül egymás után.
3) A tartályról készített ábrák nem követi a sem műszaki rajz szabályait, és a feladathoz sem igazodnak túl jól, mert a számításban előforduló mennyiségek nagyrésze nincs megjelölve.
4) A sebesség-idő (v-t) és a szint-idő (h-t) függvény is t-v koordinátarendszerben szerepel. Egyeneletet nem látok hozzájuk, pedig kellene, és az alakjuk sem tűnik jónak.
5) A végállapotbeli szintet a térfogat feléből lehet meghatározni, amihez pedig a megfelelő körszeletek területét és felettük lévő hasábok térfogatát kell kiszámolni. Az 5/8 D a vízoszlop magasságának a fele, nem a térfogat feléhez tartozó szint. A helyes szint kb. 1,066 m lesz.
