### ISSUE TITLE
Kidolgozott/3. feladat

### ISSUE THREAD

**Issue by budaibarna** [PE-MK-JAKI-H/MAFGY#62]
Tisztelt Tanár Úr!

Kérem ellenőrizze az elkészített feladatomat, ami a kidolgozott példákból a 3. Köszönöm!

**Comment by Szalay** [comment]
A következő hibákat kellene javítani:
1) A sűrűség jelölését és értékét ki kellene javítani. Nemp, hanem \varrho, és az egybetűs indexek nagybetűsek legyenek! A mértékegység a feladatgyűjteményben is rossz.
![image](https://user-images.githubusercontent.com/8204804/84936021-e71c3a00-b0d9-11ea-8434-66178e998aaf.png)

2) Az a_1 éa az a_2 méretvonalai ne legyenek vastagok!
3) A teljes differenciált jelölő d a \dif paranccsal szedhető.
4) Az ábrán is helytelen a sűrűség jelölése.
5) A tengelyeket jelölő x és y is legyen egyenletben!
6) A karikák a rajzon legyenek felül és legyenek fehéren kitöltve, mert most a hozzájuk kapcsolódó vonaalk rájuk lógnak.

Ha feltöltöd a javítást, akkor ne maradjon ki az MAFGY.tex és a lefordított PDF.

**Comment by budaibarna** [comment]
Tisztelt Tanár Úr!

Javítottam a hibákat, kérem nézze meg ismét!

**Comment by Szalay** [comment]
Átnéztem és pontoztam, az eredményt megtalálod a Google-táblázatban.
