### ISSUE TITLE
K1/15 áramlástan gyakorlati példa, I3IHGZ

### ISSUE THREAD

**Issue by Botyporus** [PE-MK-JAKI-H/MAFGY#63]
Kijavítottam a hibákat amiket leírt.

**Comment by Szalay** [comment]
Frissítettem a pontozást.

**Comment by Szalay** [comment]
A másik feladatod is el fogod készíteni?

**Comment by Botyporus** [comment]
Az elméleti tételt? igen. (megpróbálom :P)
