### ISSUE TITLE
MAFGY 1/3B (LHS5L1)

### ISSUE THREAD

**Issue by Szalay** [PE-MK-JAKI-H/MAFGY#66]
Itt kellett volna kérni az ellenőrzést.

**Comment by Szalay** [comment]
Átnéztem és pontoztam a jelenlegi állapot alapján, az eredményt megtalálod a Google-táblázatban.

Ha szeretnél javítani a beadandón, akkor írok egy listát a hibákról.

**Comment by zsoharzs** [comment]
Köszönöm szépen, elfogadom így, nem javítanék rajta.
