### ISSUE TITLE
MAFGY 1/4B Feladat ellenőrzése (XLLO4T)

### ISSUE THREAD

**Issue by mBeeci** [PE-MK-JAKI-H/MAFGY#67]
Tisztelt Tanár Úr!

Elkészítettem a feladatot.
Kérem legyen szíves ellenőrizni.

Segítségét előre is köszönöm!

Üdvözlettel:
Moharos Béla
XLLO4T

**Comment by Szalay** [comment]
Megnéztem, az apróbb hibákat megjelöltem itt: https://github.com/PE-MK-JAKI-H/MAFGY/commit/ff96b7eafbbe6d3f10638549bc43eb6f26fce50d

Két nagyobb javítani valót kiemelnék:
1) A második ábránál a térfogatokat ellenőrizni kellene.
2) A vektorábra arányai nem egészen jók, nem merőleges a térerő vektor a felszínre.

**Comment by mBeeci** [comment]
Köszönöm az ellenőrzést!

Elvégeztem a kért javításokat:

1. A térfogatokhoz részletes számításokat készítettem.
2. A térerő vektort amennyire tudtam merőlegessé tettem a felszínnel. 

Valamint a megjelölt formai hibákat is javítottam.

Kérem legyen szíves ellenőrizni újra.

Segítségét előre is köszönöm!

**Comment by Szalay** [comment]
Nincs feltöltve a frissebb változat.

**Comment by mBeeci** [comment]
Elnézést kérek, valahol elrontottam, de ha minden igaz már feltöltöttem.

**Comment by Szalay** [comment]
Átnéztem és pontoztam, az eredményt megtalálod a Google-táblázatban.
