### ISSUE TITLE
MAFGY 3/7 VZTGC1

### ISSUE THREAD

**Issue by Szalay** [PE-MK-JAKI-H/MAFGY#69]
A számítás menete alapvetően rendben van, de látok néhány hibát:
1) A vektorok jelölésére ode kellene figyelni. Az ábrán, ahol kellene jelölni őket, nincsenek jelölve, az egyenletekben viszont vektorok szerepelnek, ami helytelen.
2) Az ábrán nincs jelölve az ellenőrző felület és térfogat.
3) Az impulzuserőket J-vel, a sebességeket kis v-vel kellene jelölni.  
4) A lépések közé kellene írni szöveges magyarázatokat. 2-3 egyenletnél több ne legyen közvetlenül egymás után.

**Comment by UhrinA** [comment]
Tisztelt Tanárúr!
Újra rajzoltam az ábrát, igyekeztem az Ön által írtak alapján javítani rajta, kérem nézze meg hogy így már helyes-e.
![áramtan ábra](https://user-images.githubusercontent.com/63113222/85206504-e2969200-b322-11ea-9121-9259c1ae2314.jpg)

**Comment by Szalay** [comment]
Az impulzuserők kifele mutassanak!

**Comment by UhrinA** [comment]
Rendben az impulzus erőket javítom! 
Az ellenőrző felület és a térfogat jelölések megfelelőek úgy ahogy az ábrán vannak?

**Comment by Szalay** [comment]
A szaggatott vonal a szokásos jelölés, de nem szövegesen szokás megjelölni, hanem V_0 a térfogat és \partial V_0 a felület jele.

**Comment by UhrinA** [comment]
Tisztelt Tanárút!
Olyan problémám van hogy a törzsdokumentumomban a JakiAlap és JakiTikz fájlok elérési útját meg kellett változtatnom, mert mielőtt ezt meg tettem azt jelezte hogy ezek a fájlok léteznek és csak utána ismerte fel őket. A változtatásról csatolok képet. Az a kérdésem hogy ha így commitolom az is jó vagy valamit változtatnom kéne rajta esetleg a fájlokat rakjam inkább másik mappába? 
![Jakialap változtatás](https://user-images.githubusercontent.com/63113222/85222553-589b0780-b3bc-11ea-9bde-0fb1bdf4d9bd.PNG)

**Comment by Szalay** [comment]
Átnéztem és pontoztam a jelenlegi állapot alapján, az eredményt megtalálod a Google-táblázatban.

**Comment by UhrinA** [comment]
Tisztelt Tanár Úr! 
Megnéztem a Google-táblázatban a pontjaimat, és ezt a jegyet elfogadom.
