### ISSUE TITLE
Feladat 3/10

### ISSUE THREAD

**Issue by qiseel** [PE-MK-JAKI-H/MAFGY#7]
Jó napot kívánok ! Ma szeretnék nekiállni a 3/10-es feladatnak és latexban és a számolásban minek kell szerepelnie a 75%-os részből?mire figyeljek?

**Comment by Szalay** [comment]
1) Előszöris arra, hogy a feketével bekeretezett részek egybetartozó feladatok :)
2) Közben láttam, hogy a síklapos feladattól kitörölted magad, ha már megvolt belőle valami, azt a végén beszámítom, ha szükség lesz rá.
3) A 3/10-ben a Borda-féle kifolyónyílást kell összehozni a változó vízszintes kifolyással. Úgy rémlik, valaki csinálja ennek az elméletét, igazából onnan átemelhetsz részeket, de itt nem kell annyira részletes levezetés az általános részről, inkább a tartályalak és a kifolyónyílás beépítését kell kiemelni.
4) Az ábrán az ellenőrző felület és a vizsgált áramvonal legyen feltüntetve.

A fentieken felül a Moodle-be feltöltöttem a pontozási sémát.

**Comment by qiseel** [comment]
Igen kitöröltem magamat azért hogy legyen hely annak aki még nem választott. És köszönöm hogy beszámítja ha netán kelleni fog a pont!
