### ISSUE TITLE
Ellenőrzés A115BP

### ISSUE THREAD

**Issue by HorvathBencee** [PE-MK-JAKI-H/MAFGY#71]
Tisztelt Tanár Úr!
Elkészültem a feladattal (MAFGY, H/17). Kérem nézze át, hogy jó-e így vagy kell még javítani rajta valamit.
Köszönöm!

**Comment by Szalay** [comment]
Átnéztem és pontoztam a jelenlegi állapot alapján, az eredményt megtalálod a Google-táblázatban.

Az apróbb hibákat nem javíttatom ki, mert a jegyen nem változtatna.

**Comment by HorvathBencee** [comment]
Koszonom szepen!

Szalay <notifications@github.com> (időpont: 2020. jún. 22., H, 17:19) ezt
írta:
