### ISSUE TITLE
2/10-es feladat ellenőrzése

### ISSUE THREAD

**Issue by MDani0521** [PE-MK-JAKI-H/MAFGY#72]
Tisztelt Tanár Úr!
Feltöltöttem a beadandó feladatomat (Csővezetékben áramló levegő).
Legyen szíves ellenőrízni.

**Comment by Szalay** [comment]
Átnéztem és pontoztam, az eredményt megtalálod a Google-táblázatban.

**Comment by MDani0521** [comment]
Köszönöm!
A szerdai vizsgát felvettem. Ahhoz hogy megkapjam a jegyet meg kell jelenni az online vizsgán, vagy elegendő csak felvenni?

**Comment by Szalay** [comment]
Nem kell megjelenni, elegendő a jelentkezés.
