### ISSUE TITLE
NLT9X4 1/7B

### ISSUE THREAD

**Issue by rothandrea** [PE-MK-JAKI-H/MAFGY#75]
Tisztelt Tanár Úr!

Feltöltöttem a feladatom, ha ideje engedi, ellenőrizné? Illetve megírná, hogy a jelenlegi állapotában hány %-os? 

Köszönöm szépen!

**Comment by Szalay** [comment]
Átnéztem és pontoztam a jelenlegi állapot alapján, az eredményt megtalálod a Google-táblázatban.
