### ISSUE TITLE
FDE7S8 feladat ellenőrzés/leadás; vizsgahelyek

### ISSUE THREAD

**Issue by CsTD-PE** [PE-MK-JAKI-H/MAFGY#77]
Tanár Úr!
Feltöltöttem a 3/1es feladatot, legyen szíves átnézni és ha lehet, véglegesen leadnám. Legyen szíves vizsgahelyet bővíttetni, mert nem tudtam felvenni!

**Comment by Szalay** [comment]
Nincs feltöltve a beadandó.

**Comment by CsTD-PE** [comment]
ELvileg most láthatónak kell lennie.

**Comment by Szalay** [comment]
Átnéztem és pontoztam, az eredményt megtalálod a Google-táblázatban.

**Comment by Szalay** [comment]
A szerdai vizsga létszámkorlátját már megnöveltettem.

**Comment by CsTD-PE** [comment]
Köszönöm!
Igen azóta láttam, most azt várom hogy jóváírják az utalást, hogy a pótdíjat befizethessem és felvehessem.
Érdemes javítanom még rajta? Utolsó tárgy, szóval most már ráérek

**Comment by Szalay** [comment]
1) Technikailag rendbe kellene tenni, hogy ott legyenek a fájlok, ahol lenniük kell.
2) Az egyenletekben elég sok hiba van.
3) Az ábrákon egymásra lógnak elemek, amiknek nem kellene.
4) A részfeladatokhoz is kellene írni egy-két mondatnyi magyarázatot.

**Comment by CsTD-PE** [comment]
Amennyire tudtam javítottam a problémákat. A képleteket átnéztem, de csak vagy 3 elütésre akadtam. Nem tudok rájönni mit rontottam el. A többi problémát igyekeztem orvosolni.

**Comment by Szalay** [comment]
Egy kicsit jobb lett, de csak egy kicsit.
