### ISSUE TITLE
Megoldás ábra nélkül (4/10)

### ISSUE THREAD

**Issue by bertokdani** [PE-MK-JAKI-H/MAFGY#8]
@Szalay Tanár Úr!

Itt az első megoldásom ábra nélkül a 4/10-es feladathoz, kérem nézze át, hogy mit javítsak, valamint segítséget szeretnék kérni az ábrával kapcsolatban akár videó/elearning formájában! Előre is köszönöm!

![image](https://user-images.githubusercontent.com/63049741/79311117-3d63d580-7efd-11ea-842e-46cdf10a4528.png)
![image](https://user-images.githubusercontent.com/63049741/79311157-4bb1f180-7efd-11ea-85fa-d2dded8acc84.png)
![image](https://user-images.githubusercontent.com/63049741/79311177-54a2c300-7efd-11ea-9426-1e598b2803bd.png)
![image](https://user-images.githubusercontent.com/63049741/79311200-5cfafe00-7efd-11ea-8fc5-74e118bd6dc2.png)

**Comment by Szalay** [comment]
Képeket nem kell ilyenkor feltölteni, elég kérni az ellenőrzést, és átállok a te ágadra, lefordítom, és a a forráshoz írom a megjegyzéseket.

**Comment by Szalay** [comment]
A számítás menete rendben van, a számértékek helyesek (a m^2/s^2-ből arra gondolok, hogy a Wolfram jegyzet alapján dolgozhattál, ami nem baj, sőt, ha így volt, jól tetted).

Az ábrakészítésre a jövő heti órán visszatérünk, illetve a Moodle-beli útmutatót még bővíteni fogom.
