### ISSUE TITLE
Műszaki áramlástan beadandó CRB25Y

### ISSUE THREAD

**Issue by sebokalex** [PE-MK-JAKI-H/MAFGY#80]
Tisztelt Tanár Úr!

Feltöltöttem az általam választott feladatokat, ha megfelel önnek akkor véglegesen is be szeretném adni a beadandót.

**Comment by sebokalex** [comment]
2darab MAEK és 1darab MAFGY voltak a választott feladatjaim.

**Comment by Szalay** [comment]
Átnéztem és pontoztam mindhárom feladatot, az eredményt megtalálod a Google-táblázatban.

**Comment by sebokalex** [comment]
Rendben, köszönöm Tanár Úr el szeretném fogadni az eredményt.

**Comment by Szalay** [comment]
Akkor már csak annyi dolgod van, hogy jelentkezz vizsgára.
