### ISSUE TITLE
h5/11 Pilot Prandtl cső

### ISSUE THREAD

**Issue by KaAnRi3919** [PE-MK-JAKI-H/MAFGY#84]

**Comment by Szalay** [comment]
Száz pontnyi feladatot keleltt volna választani és megoldani, de ehelyett egy 100 és egy 50 pontos feladatot kezdtél megoldani, és hát egyiket sem sikerült elfogadható szinten elkészíteni sem tartalmi, sem formai, sem technikai szempontból. 

A beadandó állapota alapján azt javaslom, hogy elsőként olvasd el segédletet, amit Moodle-be írtam. Eztuán olyan szintre kellene hozni a beadandót, hogy a hozzá tartozó fájlok a megfelelő helyen legyenek, és lefordítható legyen, majd ezután a feltöltésnél feltölteni az összes fájlt. A Moodle-beli segédletben találsz példát a három egyenelettípusra, ezek közül mindig a megfelelőt kellene használni. 2-3 egyenlet után illendő és ésszerű is egy-egy mondatnyi magyarázatot beiktatni. Ábra is tartozik mindegyik feladathoz. A Moodle-ben megtalálod a mennyiségek elvárt jelöléseit. 

Biztos, ami biztos, csatolok két képet arról, hogy nálam hogy néz ki, amit feltöltöttél:

![image](https://user-images.githubusercontent.com/8204804/85448433-f8ac8880-b596-11ea-9c78-702998ad9ae9.png)

![image](https://user-images.githubusercontent.com/8204804/85448383-e9c5d600-b596-11ea-8526-1127ff246afc.png)

Ui.: a csillag nem szorzásjel.
