### ISSUE TITLE
H5_11 és H4_7B javitott

### ISSUE THREAD

**Issue by KaAnRi3919** [PE-MK-JAKI-H/MAFGY#86]
Tisztelt Tanár úr!

Mellékleltem a beadandót javítva. Elnézést kérek a késésért!

Tisztelettel:
Katona András Richárd (DD8MYG)

**Comment by Szalay** [comment]
Megnéztem a feltöltött és levélben küldött változatokat is, és frissítettem az értékelést. Még mindig nagyon sok a hiba, de az elfogadható szintet már eléri a beadandó. Időközben már beírtam a jegyet a Neptunba a tegnapi állapot alapján, de most frissítettem azt is.
