### ISSUE TITLE
H5 feladat megoldása

### ISSUE THREAD

**Issue by gerbovitsditta** [PE-MK-JAKI-H/MAFGY#9]
[Áramlástan.H5.pdf](https://github.com/PE-MK-JAKI-H/MAFGY/files/4480851/Aramlastan.H5.pdf)

**Comment by gerbovitsditta** [comment]
Tisztelt Tanár Úr!
A kézzel írt megoldást linkeltem. Érdeklődni szeretnék, hogy az ábrát ehhez a feladathoz a kézzel rajzolt ábra alapján lehet-e majd készíteni, vagy a feladatgyűjteménybeli ábrát igyekezzek lemásolni?
Előre is köszönöm a választ!

**Comment by Szalay** [comment]
A feladatmegoldás menete rendben van, de az elektronikus váltizatban a főbb lépésekhez legyenek szöveges magyarázatok. A 0,223 métert rosszul váltod át, de a helyes értékkel számolsz tovább, így aztán a végeredmény is jó. 

Az ábrák között nem látok nagy különbséget, a forgástengely hiányzi ka kézzel rajzolt ábrádról, az átmérőjel a d előtt kellene legyen és a méretvonal a kívüllévő nyilak között is megrajzolandó, valamint a sugár jelöléséről hiányzik a nyílfej, de ezen kívül azonosak.

Az első lépés magyarázatában jelenjen meg, hogy a potenciálfelszínek egyenletéről van szó, és ez az amire igazából az ábrán is oda kell majd figyelni.

**Comment by Szalay** [comment]
Még egy megjegyzés: a fájlnév majd ne h5 legyen, hanem valahogy az is jelenjen meg benne, hogy az első fejezet 5. feladata. Meg a neptun kódod, a Moodle-bel iminta szerint.
